package com.tecladoapp.keyboard

data class EmojiEntry(val emoji: String, val keywords: List<String>)

object EmojiData {

    private val smileys = listOf(
        EmojiEntry("😀", listOf("feliz", "sonrisa", "contento")),
        EmojiEntry("😃", listOf("feliz", "sonrisa")),
        EmojiEntry("😄", listOf("feliz", "risa")),
        EmojiEntry("😁", listOf("feliz", "sonrisa", "dientes")),
        EmojiEntry("😆", listOf("risa", "jaja")),
        EmojiEntry("😅", listOf("risa", "nervioso", "sudor")),
        EmojiEntry("🤣", listOf("risa", "carcajada")),
        EmojiEntry("😂", listOf("risa", "llorar de risa", "jaja")),
        EmojiEntry("🙂", listOf("sonrisa", "leve")),
        EmojiEntry("🙃", listOf("al reves", "sonrisa")),
        EmojiEntry("😉", listOf("guiño")),
        EmojiEntry("😊", listOf("feliz", "sonrisa", "timido")),
        EmojiEntry("😇", listOf("angel", "inocente")),
        EmojiEntry("🥰", listOf("amor", "enamorado", "cariño")),
        EmojiEntry("😍", listOf("amor", "ojos de corazon")),
        EmojiEntry("🤩", listOf("estrellas", "asombrado")),
        EmojiEntry("😘", listOf("beso")),
        EmojiEntry("😗", listOf("beso")),
        EmojiEntry("😚", listOf("beso")),
        EmojiEntry("😙", listOf("beso")),
        EmojiEntry("😋", listOf("delicioso", "rico", "sabroso")),
        EmojiEntry("😛", listOf("lengua")),
        EmojiEntry("😜", listOf("guiño", "lengua", "broma")),
        EmojiEntry("🤪", listOf("loco", "broma")),
        EmojiEntry("😝", listOf("lengua")),
        EmojiEntry("🤑", listOf("dinero")),
        EmojiEntry("🤗", listOf("abrazo")),
        EmojiEntry("🤭", listOf("risa", "silencio")),
        EmojiEntry("🤫", listOf("silencio", "shh")),
        EmojiEntry("🤔", listOf("pensando", "duda")),
        EmojiEntry("🤐", listOf("cierra la boca", "callado")),
        EmojiEntry("🤨", listOf("duda", "ceja")),
        EmojiEntry("😐", listOf("neutral", "serio")),
        EmojiEntry("😑", listOf("sin expresion")),
        EmojiEntry("😶", listOf("sin boca", "callado")),
        EmojiEntry("😏", listOf("picaro", "sonrisa")),
        EmojiEntry("😒", listOf("fastidio", "cansado")),
        EmojiEntry("🙄", listOf("ojos en blanco")),
        EmojiEntry("😬", listOf("nervioso", "mueca")),
        EmojiEntry("🤥", listOf("mentira", "pinocho")),
        EmojiEntry("😌", listOf("alivio", "tranquilo")),
        EmojiEntry("😔", listOf("triste", "pensativo")),
        EmojiEntry("😪", listOf("sueño", "cansado")),
        EmojiEntry("🤤", listOf("baba", "delicioso")),
        EmojiEntry("😴", listOf("dormir", "sueño")),
        EmojiEntry("😷", listOf("enfermo", "cubrebocas")),
        EmojiEntry("🤒", listOf("fiebre", "enfermo")),
        EmojiEntry("🤕", listOf("herido", "vendaje")),
        EmojiEntry("🤢", listOf("asco", "nausea")),
        EmojiEntry("🤮", listOf("vomito", "asco")),
        EmojiEntry("🤧", listOf("estornudo", "resfriado")),
        EmojiEntry("🥵", listOf("calor")),
        EmojiEntry("🥶", listOf("frio")),
        EmojiEntry("🥴", listOf("mareado", "borracho")),
        EmojiEntry("😵", listOf("mareado", "aturdido")),
        EmojiEntry("🤯", listOf("mente explota", "sorpresa")),
        EmojiEntry("🤠", listOf("vaquero")),
        EmojiEntry("🥳", listOf("fiesta", "celebrar")),
        EmojiEntry("😎", listOf("genial", "lentes de sol")),
        EmojiEntry("🤓", listOf("nerd", "lentes")),
        EmojiEntry("🧐", listOf("monoculo", "elegante")),
        EmojiEntry("😕", listOf("confundido")),
        EmojiEntry("😟", listOf("preocupado")),
        EmojiEntry("🙁", listOf("triste")),
        EmojiEntry("😮", listOf("sorpresa")),
        EmojiEntry("😯", listOf("sorpresa")),
        EmojiEntry("😲", listOf("asombrado")),
        EmojiEntry("😳", listOf("sonrojado", "sorpresa")),
        EmojiEntry("🥺", listOf("suplica", "tierno")),
        EmojiEntry("😦", listOf("sorpresa")),
        EmojiEntry("😧", listOf("angustia")),
        EmojiEntry("😨", listOf("miedo")),
        EmojiEntry("😰", listOf("miedo", "sudor")),
        EmojiEntry("😥", listOf("triste", "alivio")),
        EmojiEntry("😢", listOf("triste", "llorar")),
        EmojiEntry("😭", listOf("llorar mucho", "triste")),
        EmojiEntry("😱", listOf("miedo", "sorpresa", "grito")),
        EmojiEntry("😖", listOf("confundido", "mal")),
        EmojiEntry("😣", listOf("frustrado")),
        EmojiEntry("😞", listOf("decepcionado")),
        EmojiEntry("😓", listOf("sudor", "cansado")),
        EmojiEntry("😩", listOf("cansado", "agotado")),
        EmojiEntry("😫", listOf("agotado")),
        EmojiEntry("🥱", listOf("bostezo", "sueño")),
        EmojiEntry("😤", listOf("enojado", "orgullo")),
        EmojiEntry("😡", listOf("enojado", "furioso")),
        EmojiEntry("😠", listOf("enojado")),
        EmojiEntry("🤬", listOf("groseria", "enojado")),
        EmojiEntry("😈", listOf("diablo", "travieso")),
        EmojiEntry("👿", listOf("diablo enojado")),
        EmojiEntry("💀", listOf("calavera", "muerte")),
        EmojiEntry("☠️", listOf("calavera", "peligro")),
        EmojiEntry("💩", listOf("caca")),
        EmojiEntry("🤡", listOf("payaso")),
        EmojiEntry("👹", listOf("ogro")),
        EmojiEntry("👺", listOf("duende")),
        EmojiEntry("👻", listOf("fantasma")),
        EmojiEntry("👽", listOf("extraterrestre")),
        EmojiEntry("🤖", listOf("robot")),
        EmojiEntry("😺", listOf("gato feliz")),
        EmojiEntry("😹", listOf("gato risa")),
        EmojiEntry("😻", listOf("gato amor")),
        EmojiEntry("🙈", listOf("mono no ver")),
        EmojiEntry("🙉", listOf("mono no oir")),
        EmojiEntry("🙊", listOf("mono no hablar")),
        EmojiEntry("💋", listOf("beso", "labios")),
        EmojiEntry("💌", listOf("carta de amor")),
        EmojiEntry("💘", listOf("flecha", "amor")),
        EmojiEntry("💝", listOf("regalo", "corazon")),
        EmojiEntry("💖", listOf("corazon brillante")),
        EmojiEntry("💗", listOf("corazon creciendo")),
        EmojiEntry("💓", listOf("corazon latiendo")),
        EmojiEntry("💞", listOf("corazones girando")),
        EmojiEntry("💕", listOf("corazones")),
        EmojiEntry("💟", listOf("corazon decorativo")),
        EmojiEntry("❣️", listOf("exclamacion corazon")),
        EmojiEntry("💔", listOf("corazon roto", "triste")),
        EmojiEntry("❤️", listOf("amor", "corazon rojo")),
        EmojiEntry("🧡", listOf("corazon naranja")),
        EmojiEntry("💛", listOf("corazon amarillo")),
        EmojiEntry("💚", listOf("corazon verde")),
        EmojiEntry("💙", listOf("corazon azul")),
        EmojiEntry("💜", listOf("corazon morado")),
        EmojiEntry("🤎", listOf("corazon cafe")),
        EmojiEntry("🖤", listOf("corazon negro")),
        EmojiEntry("🤍", listOf("corazon blanco"))
    )

    private val gestos = listOf(
        EmojiEntry("👋", listOf("hola", "adios", "saludo")),
        EmojiEntry("🤚", listOf("mano")),
        EmojiEntry("🖐️", listOf("mano abierta")),
        EmojiEntry("✋", listOf("alto", "mano")),
        EmojiEntry("🖖", listOf("saludo vulcano")),
        EmojiEntry("👌", listOf("ok", "perfecto")),
        EmojiEntry("🤌", listOf("italiano", "gesto")),
        EmojiEntry("🤏", listOf("pellizco", "poquito")),
        EmojiEntry("✌️", listOf("paz", "victoria")),
        EmojiEntry("🤞", listOf("dedos cruzados", "suerte")),
        EmojiEntry("🤟", listOf("te amo", "seña")),
        EmojiEntry("🤘", listOf("rock")),
        EmojiEntry("🤙", listOf("llamame")),
        EmojiEntry("👈", listOf("apunta izquierda")),
        EmojiEntry("👉", listOf("apunta derecha")),
        EmojiEntry("👆", listOf("apunta arriba")),
        EmojiEntry("🖕", listOf("dedo")),
        EmojiEntry("👇", listOf("apunta abajo")),
        EmojiEntry("☝️", listOf("apunta arriba")),
        EmojiEntry("👍", listOf("bien", "like", "pulgar arriba")),
        EmojiEntry("👎", listOf("mal", "pulgar abajo")),
        EmojiEntry("✊", listOf("puño")),
        EmojiEntry("👊", listOf("puño", "choca")),
        EmojiEntry("🤛", listOf("puño izquierda")),
        EmojiEntry("🤜", listOf("puño derecha")),
        EmojiEntry("👏", listOf("aplausos", "bravo")),
        EmojiEntry("🙌", listOf("celebrar", "manos arriba")),
        EmojiEntry("👐", listOf("manos abiertas")),
        EmojiEntry("🤲", listOf("manos juntas")),
        EmojiEntry("🤝", listOf("trato", "acuerdo")),
        EmojiEntry("🙏", listOf("gracias", "por favor", "rezar")),
        EmojiEntry("✍️", listOf("escribir")),
        EmojiEntry("💅", listOf("uñas")),
        EmojiEntry("🤳", listOf("selfie")),
        EmojiEntry("💪", listOf("fuerza", "musculo")),
        EmojiEntry("🦾", listOf("brazo biónico")),
        EmojiEntry("🦵", listOf("pierna")),
        EmojiEntry("🦶", listOf("pie")),
        EmojiEntry("👂", listOf("oreja")),
        EmojiEntry("👃", listOf("nariz")),
        EmojiEntry("🧠", listOf("cerebro")),
        EmojiEntry("👀", listOf("ojos")),
        EmojiEntry("👁️", listOf("ojo")),
        EmojiEntry("👅", listOf("lengua")),
        EmojiEntry("👄", listOf("boca", "labios"))
    )

    private val animales = listOf(
        EmojiEntry("🐶", listOf("perro")),
        EmojiEntry("🐱", listOf("gato")),
        EmojiEntry("🐭", listOf("raton")),
        EmojiEntry("🐹", listOf("hamster")),
        EmojiEntry("🐰", listOf("conejo")),
        EmojiEntry("🦊", listOf("zorro")),
        EmojiEntry("🐻", listOf("oso")),
        EmojiEntry("🐼", listOf("panda")),
        EmojiEntry("🐨", listOf("koala")),
        EmojiEntry("🐯", listOf("tigre")),
        EmojiEntry("🦁", listOf("leon")),
        EmojiEntry("🐮", listOf("vaca")),
        EmojiEntry("🐷", listOf("cerdo")),
        EmojiEntry("🐽", listOf("nariz de cerdo")),
        EmojiEntry("🐸", listOf("rana")),
        EmojiEntry("🐵", listOf("mono")),
        EmojiEntry("🐔", listOf("gallina")),
        EmojiEntry("🐧", listOf("pinguino")),
        EmojiEntry("🐦", listOf("pajaro")),
        EmojiEntry("🐤", listOf("pollito")),
        EmojiEntry("🦆", listOf("pato")),
        EmojiEntry("🦅", listOf("aguila")),
        EmojiEntry("🦉", listOf("buho")),
        EmojiEntry("🦇", listOf("murcielago")),
        EmojiEntry("🐺", listOf("lobo")),
        EmojiEntry("🐗", listOf("jabali")),
        EmojiEntry("🐴", listOf("caballo")),
        EmojiEntry("🦄", listOf("unicornio")),
        EmojiEntry("🐝", listOf("abeja")),
        EmojiEntry("🐛", listOf("oruga")),
        EmojiEntry("🦋", listOf("mariposa")),
        EmojiEntry("🐌", listOf("caracol")),
        EmojiEntry("🐞", listOf("mariquita")),
        EmojiEntry("🐜", listOf("hormiga")),
        EmojiEntry("🦟", listOf("mosquito")),
        EmojiEntry("🕷️", listOf("araña")),
        EmojiEntry("🦂", listOf("escorpion")),
        EmojiEntry("🐢", listOf("tortuga")),
        EmojiEntry("🐍", listOf("serpiente")),
        EmojiEntry("🦎", listOf("lagartija")),
        EmojiEntry("🦖", listOf("dinosaurio")),
        EmojiEntry("🦕", listOf("dinosaurio")),
        EmojiEntry("🐙", listOf("pulpo")),
        EmojiEntry("🦑", listOf("calamar")),
        EmojiEntry("🦐", listOf("camaron")),
        EmojiEntry("🦀", listOf("cangrejo")),
        EmojiEntry("🐡", listOf("pez globo")),
        EmojiEntry("🐠", listOf("pez")),
        EmojiEntry("🐟", listOf("pez")),
        EmojiEntry("🐬", listOf("delfin")),
        EmojiEntry("🐳", listOf("ballena")),
        EmojiEntry("🐋", listOf("ballena")),
        EmojiEntry("🦈", listOf("tiburon")),
        EmojiEntry("🐊", listOf("cocodrilo")),
        EmojiEntry("🐆", listOf("leopardo")),
        EmojiEntry("🦓", listOf("cebra")),
        EmojiEntry("🦍", listOf("gorila")),
        EmojiEntry("🐘", listOf("elefante")),
        EmojiEntry("🦏", listOf("rinoceronte")),
        EmojiEntry("🦛", listOf("hipopotamo")),
        EmojiEntry("🐪", listOf("camello")),
        EmojiEntry("🐫", listOf("camello")),
        EmojiEntry("🦒", listOf("jirafa")),
        EmojiEntry("🦘", listOf("canguro")),
        EmojiEntry("🐄", listOf("vaca")),
        EmojiEntry("🐎", listOf("caballo")),
        EmojiEntry("🐑", listOf("oveja")),
        EmojiEntry("🐐", listOf("cabra")),
        EmojiEntry("🐕", listOf("perro")),
        EmojiEntry("🐩", listOf("caniche")),
        EmojiEntry("🐈", listOf("gato")),
        EmojiEntry("🐓", listOf("gallo")),
        EmojiEntry("🦃", listOf("pavo")),
        EmojiEntry("🕊️", listOf("paloma")),
        EmojiEntry("🐇", listOf("conejo")),
        EmojiEntry("🐿️", listOf("ardilla")),
        EmojiEntry("🦔", listOf("erizo")),
        EmojiEntry("🐾", listOf("huellas")),
        EmojiEntry("🌵", listOf("cactus")),
        EmojiEntry("🌲", listOf("arbol")),
        EmojiEntry("🌳", listOf("arbol")),
        EmojiEntry("🌴", listOf("palmera")),
        EmojiEntry("🌱", listOf("planta")),
        EmojiEntry("🌿", listOf("hierba")),
        EmojiEntry("☘️", listOf("trebol")),
        EmojiEntry("🍀", listOf("suerte", "trebol")),
        EmojiEntry("🎋", listOf("bambu")),
        EmojiEntry("🍃", listOf("hojas")),
        EmojiEntry("🍂", listOf("otoño")),
        EmojiEntry("🍁", listOf("otoño", "hoja")),
        EmojiEntry("🍄", listOf("hongo")),
        EmojiEntry("🌾", listOf("trigo")),
        EmojiEntry("💐", listOf("ramo de flores")),
        EmojiEntry("🌷", listOf("tulipan")),
        EmojiEntry("🌹", listOf("rosa")),
        EmojiEntry("🥀", listOf("flor marchita")),
        EmojiEntry("🌺", listOf("flor")),
        EmojiEntry("🌸", listOf("flor de cerezo")),
        EmojiEntry("🌼", listOf("flor")),
        EmojiEntry("🌻", listOf("girasol")),
        EmojiEntry("☀️", listOf("sol", "clima")),
        EmojiEntry("🌤️", listOf("sol nube")),
        EmojiEntry("⛅", listOf("nublado")),
        EmojiEntry("☁️", listOf("nube")),
        EmojiEntry("🌦️", listOf("lluvia sol")),
        EmojiEntry("🌧️", listOf("lluvia")),
        EmojiEntry("⛈️", listOf("tormenta")),
        EmojiEntry("🌩️", listOf("rayo")),
        EmojiEntry("🌨️", listOf("nieve")),
        EmojiEntry("❄️", listOf("nieve", "copo")),
        EmojiEntry("☃️", listOf("muñeco de nieve")),
        EmojiEntry("⛄", listOf("muñeco de nieve")),
        EmojiEntry("🌬️", listOf("viento")),
        EmojiEntry("💨", listOf("viento", "rapido")),
        EmojiEntry("🌪️", listOf("tornado")),
        EmojiEntry("🌈", listOf("arcoiris")),
        EmojiEntry("☂️", listOf("paraguas")),
        EmojiEntry("☔", listOf("lluvia", "paraguas")),
        EmojiEntry("⚡", listOf("rayo")),
        EmojiEntry("🌙", listOf("luna", "noche")),
        EmojiEntry("⭐", listOf("estrella")),
        EmojiEntry("🌟", listOf("estrella brillante")),
        EmojiEntry("✨", listOf("brillo", "magia")),
        EmojiEntry("🔥", listOf("fuego", "genial")),
        EmojiEntry("💧", listOf("gota", "agua")),
        EmojiEntry("🌊", listOf("ola", "mar"))
    )

    private val comida = listOf(
        EmojiEntry("🍎", listOf("manzana", "fruta")),
        EmojiEntry("🍏", listOf("manzana verde")),
        EmojiEntry("🍊", listOf("naranja")),
        EmojiEntry("🍋", listOf("limon")),
        EmojiEntry("🍌", listOf("platano")),
        EmojiEntry("🍉", listOf("sandia")),
        EmojiEntry("🍇", listOf("uvas")),
        EmojiEntry("🍓", listOf("fresa")),
        EmojiEntry("🫐", listOf("arandanos")),
        EmojiEntry("🍈", listOf("melon")),
        EmojiEntry("🍒", listOf("cerezas")),
        EmojiEntry("🍑", listOf("durazno")),
        EmojiEntry("🥭", listOf("mango")),
        EmojiEntry("🍍", listOf("piña")),
        EmojiEntry("🥥", listOf("coco")),
        EmojiEntry("🥝", listOf("kiwi")),
        EmojiEntry("🍅", listOf("tomate")),
        EmojiEntry("🍆", listOf("berenjena")),
        EmojiEntry("🥑", listOf("aguacate")),
        EmojiEntry("🥦", listOf("brocoli")),
        EmojiEntry("🥬", listOf("lechuga")),
        EmojiEntry("🥒", listOf("pepino")),
        EmojiEntry("🌶️", listOf("chile", "picante")),
        EmojiEntry("🫑", listOf("pimiento")),
        EmojiEntry("🌽", listOf("maiz")),
        EmojiEntry("🥕", listOf("zanahoria")),
        EmojiEntry("🧄", listOf("ajo")),
        EmojiEntry("🧅", listOf("cebolla")),
        EmojiEntry("🥔", listOf("papa")),
        EmojiEntry("🍠", listOf("camote")),
        EmojiEntry("🥐", listOf("croissant")),
        EmojiEntry("🥯", listOf("bagel")),
        EmojiEntry("🍞", listOf("pan")),
        EmojiEntry("🥖", listOf("baguette")),
        EmojiEntry("🥨", listOf("pretzel")),
        EmojiEntry("🧀", listOf("queso")),
        EmojiEntry("🥚", listOf("huevo")),
        EmojiEntry("🍳", listOf("huevo frito")),
        EmojiEntry("🧈", listOf("mantequilla")),
        EmojiEntry("🥞", listOf("panqueques")),
        EmojiEntry("🧇", listOf("waffle")),
        EmojiEntry("🥓", listOf("tocino")),
        EmojiEntry("🥩", listOf("carne")),
        EmojiEntry("🍗", listOf("pollo")),
        EmojiEntry("🍖", listOf("hueso de carne")),
        EmojiEntry("🌭", listOf("hot dog")),
        EmojiEntry("🍔", listOf("hamburguesa")),
        EmojiEntry("🍟", listOf("papas fritas")),
        EmojiEntry("🍕", listOf("pizza")),
        EmojiEntry("🫓", listOf("pan plano")),
        EmojiEntry("🥪", listOf("sandwich")),
        EmojiEntry("🌮", listOf("taco")),
        EmojiEntry("🌯", listOf("burrito")),
        EmojiEntry("🫔", listOf("tamal")),
        EmojiEntry("🥙", listOf("pan relleno")),
        EmojiEntry("🧆", listOf("falafel")),
        EmojiEntry("🥗", listOf("ensalada")),
        EmojiEntry("🍿", listOf("palomitas")),
        EmojiEntry("🧂", listOf("sal")),
        EmojiEntry("🥫", listOf("lata de comida")),
        EmojiEntry("🍝", listOf("espagueti", "pasta")),
        EmojiEntry("🍜", listOf("sopa", "fideos")),
        EmojiEntry("🍲", listOf("guiso")),
        EmojiEntry("🍛", listOf("curry")),
        EmojiEntry("🍣", listOf("sushi")),
        EmojiEntry("🍱", listOf("bento")),
        EmojiEntry("🥟", listOf("empanadilla")),
        EmojiEntry("🍤", listOf("camaron frito")),
        EmojiEntry("🍙", listOf("bola de arroz")),
        EmojiEntry("🍚", listOf("arroz")),
        EmojiEntry("🍘", listOf("galleta de arroz")),
        EmojiEntry("🍥", listOf("pastel de pescado")),
        EmojiEntry("🥮", listOf("pastel de luna")),
        EmojiEntry("🍢", listOf("brocheta")),
        EmojiEntry("🍡", listOf("dango")),
        EmojiEntry("🍧", listOf("hielo raspado")),
        EmojiEntry("🍨", listOf("helado")),
        EmojiEntry("🍦", listOf("helado", "cono")),
        EmojiEntry("🥧", listOf("pay")),
        EmojiEntry("🧁", listOf("cupcake")),
        EmojiEntry("🍰", listOf("pastel")),
        EmojiEntry("🎂", listOf("cumpleaños", "pastel")),
        EmojiEntry("🍮", listOf("flan")),
        EmojiEntry("🍭", listOf("paleta", "dulce")),
        EmojiEntry("🍬", listOf("dulce", "caramelo")),
        EmojiEntry("🍫", listOf("chocolate")),
        EmojiEntry("🍩", listOf("dona")),
        EmojiEntry("🍪", listOf("galleta")),
        EmojiEntry("🌰", listOf("castaña")),
        EmojiEntry("🥜", listOf("cacahuate")),
        EmojiEntry("🍯", listOf("miel")),
        EmojiEntry("🥛", listOf("leche")),
        EmojiEntry("🍼", listOf("biberon")),
        EmojiEntry("☕", listOf("café")),
        EmojiEntry("🍵", listOf("te")),
        EmojiEntry("🧃", listOf("jugo")),
        EmojiEntry("🥤", listOf("bebida", "refresco")),
        EmojiEntry("🧋", listOf("bubble tea")),
        EmojiEntry("🍶", listOf("sake")),
        EmojiEntry("🍺", listOf("cerveza")),
        EmojiEntry("🍻", listOf("brindis", "cerveza")),
        EmojiEntry("🥂", listOf("brindis", "copas")),
        EmojiEntry("🍷", listOf("vino")),
        EmojiEntry("🥃", listOf("whisky")),
        EmojiEntry("🍸", listOf("coctel")),
        EmojiEntry("🍹", listOf("coctel tropical")),
        EmojiEntry("🍾", listOf("champaña")),
        EmojiEntry("🧊", listOf("hielo")),
        EmojiEntry("🥄", listOf("cuchara")),
        EmojiEntry("🍴", listOf("cubiertos")),
        EmojiEntry("🍽️", listOf("plato con cubiertos"))
    )

    private val actividades = listOf(
        EmojiEntry("⚽", listOf("futbol", "balon")),
        EmojiEntry("🏀", listOf("basquetbol")),
        EmojiEntry("🏈", listOf("futbol americano")),
        EmojiEntry("⚾", listOf("beisbol")),
        EmojiEntry("🥎", listOf("softbol")),
        EmojiEntry("🎾", listOf("tenis")),
        EmojiEntry("🏐", listOf("voleibol")),
        EmojiEntry("🏉", listOf("rugby")),
        EmojiEntry("🎱", listOf("billar")),
        EmojiEntry("🏓", listOf("ping pong")),
        EmojiEntry("🏸", listOf("badminton")),
        EmojiEntry("🥅", listOf("porteria")),
        EmojiEntry("⛳", listOf("golf")),
        EmojiEntry("🏹", listOf("arco y flecha")),
        EmojiEntry("🎣", listOf("pesca")),
        EmojiEntry("🥊", listOf("boxeo")),
        EmojiEntry("🥋", listOf("artes marciales")),
        EmojiEntry("🎽", listOf("carrera", "playera")),
        EmojiEntry("🛹", listOf("patineta")),
        EmojiEntry("🛼", listOf("patines")),
        EmojiEntry("🎿", listOf("esqui")),
        EmojiEntry("⛷️", listOf("esquiador")),
        EmojiEntry("🏂", listOf("snowboard")),
        EmojiEntry("🏋️", listOf("levantar pesas", "gimnasio")),
        EmojiEntry("🤸", listOf("gimnasia")),
        EmojiEntry("🤺", listOf("esgrima")),
        EmojiEntry("🤾", listOf("balonmano")),
        EmojiEntry("🏌️", listOf("golfista")),
        EmojiEntry("🏄", listOf("surf")),
        EmojiEntry("🏊", listOf("nadar")),
        EmojiEntry("🚴", listOf("bicicleta")),
        EmojiEntry("🚵", listOf("bicicleta montaña")),
        EmojiEntry("🧗", listOf("escalar")),
        EmojiEntry("🏆", listOf("trofeo", "ganador")),
        EmojiEntry("🥇", listOf("medalla de oro", "primer lugar")),
        EmojiEntry("🥈", listOf("medalla de plata")),
        EmojiEntry("🥉", listOf("medalla de bronce")),
        EmojiEntry("🏅", listOf("medalla")),
        EmojiEntry("🎖️", listOf("medalla militar")),
        EmojiEntry("🎗️", listOf("cinta")),
        EmojiEntry("🎫", listOf("boleto")),
        EmojiEntry("🎟️", listOf("boletos")),
        EmojiEntry("🎪", listOf("circo")),
        EmojiEntry("🎭", listOf("teatro", "mascaras")),
        EmojiEntry("🎨", listOf("arte", "pintura")),
        EmojiEntry("🎬", listOf("cine", "pelicula")),
        EmojiEntry("🎤", listOf("microfono", "cantar")),
        EmojiEntry("🎧", listOf("audifonos", "musica")),
        EmojiEntry("🎼", listOf("partitura")),
        EmojiEntry("🎹", listOf("piano")),
        EmojiEntry("🥁", listOf("bateria")),
        EmojiEntry("🎷", listOf("saxofon")),
        EmojiEntry("🎺", listOf("trompeta")),
        EmojiEntry("🎸", listOf("guitarra")),
        EmojiEntry("🪕", listOf("banjo")),
        EmojiEntry("🎻", listOf("violin")),
        EmojiEntry("🎲", listOf("dado")),
        EmojiEntry("♟️", listOf("ajedrez")),
        EmojiEntry("🎯", listOf("diana", "objetivo")),
        EmojiEntry("🎳", listOf("boliche")),
        EmojiEntry("🎮", listOf("videojuego", "control")),
        EmojiEntry("🎰", listOf("maquina tragamonedas")),
        EmojiEntry("🧩", listOf("rompecabezas")),
        EmojiEntry("🎉", listOf("fiesta", "celebracion")),
        EmojiEntry("🎊", listOf("confeti")),
        EmojiEntry("🎈", listOf("globo")),
        EmojiEntry("🎁", listOf("regalo")),
        EmojiEntry("🎀", listOf("moño")),
        EmojiEntry("🎄", listOf("navidad", "arbol")),
        EmojiEntry("🎃", listOf("halloween", "calabaza")),
        EmojiEntry("🎆", listOf("fuegos artificiales")),
        EmojiEntry("🎇", listOf("bengala")),
        EmojiEntry("🧨", listOf("dinamita")),
        EmojiEntry("🎐", listOf("campanilla")),
        EmojiEntry("🎑", listOf("luna festival"))
    )

    private val viajes = listOf(
        EmojiEntry("🚗", listOf("carro", "auto")),
        EmojiEntry("🚕", listOf("taxi")),
        EmojiEntry("🚙", listOf("suv")),
        EmojiEntry("🚌", listOf("autobus")),
        EmojiEntry("🚎", listOf("trolebus")),
        EmojiEntry("🏎️", listOf("carro de carreras")),
        EmojiEntry("🚓", listOf("policia")),
        EmojiEntry("🚑", listOf("ambulancia")),
        EmojiEntry("🚒", listOf("bomberos")),
        EmojiEntry("🚐", listOf("camioneta")),
        EmojiEntry("🛻", listOf("camioneta pickup")),
        EmojiEntry("🚚", listOf("camion")),
        EmojiEntry("🚛", listOf("camion de carga")),
        EmojiEntry("🚜", listOf("tractor")),
        EmojiEntry("🛵", listOf("motoneta")),
        EmojiEntry("🏍️", listOf("motocicleta")),
        EmojiEntry("🚲", listOf("bicicleta")),
        EmojiEntry("🛴", listOf("patineta electrica")),
        EmojiEntry("🚨", listOf("sirena")),
        EmojiEntry("🚔", listOf("patrulla")),
        EmojiEntry("🚍", listOf("autobus llegando")),
        EmojiEntry("🚘", listOf("carro de frente")),
        EmojiEntry("🚖", listOf("taxi llegando")),
        EmojiEntry("🚡", listOf("teleferico")),
        EmojiEntry("🚠", listOf("teleferico montaña")),
        EmojiEntry("🚟", listOf("tren suspendido")),
        EmojiEntry("🚃", listOf("vagon")),
        EmojiEntry("🚋", listOf("tranvia")),
        EmojiEntry("🚞", listOf("tren montaña")),
        EmojiEntry("🚝", listOf("monorriel")),
        EmojiEntry("🚄", listOf("tren bala")),
        EmojiEntry("🚅", listOf("tren bala")),
        EmojiEntry("🚈", listOf("tren ligero")),
        EmojiEntry("🚂", listOf("locomotora")),
        EmojiEntry("🚆", listOf("tren")),
        EmojiEntry("🚇", listOf("metro")),
        EmojiEntry("🚊", listOf("tranvia")),
        EmojiEntry("🚉", listOf("estacion de tren")),
        EmojiEntry("✈️", listOf("avion", "viaje")),
        EmojiEntry("🛫", listOf("avion despegando")),
        EmojiEntry("🛬", listOf("avion aterrizando")),
        EmojiEntry("🛩️", listOf("avion pequeño")),
        EmojiEntry("💺", listOf("asiento")),
        EmojiEntry("🛰️", listOf("satelite")),
        EmojiEntry("🚀", listOf("cohete", "espacio")),
        EmojiEntry("🛸", listOf("ovni")),
        EmojiEntry("🚁", listOf("helicoptero")),
        EmojiEntry("⛵", listOf("velero")),
        EmojiEntry("🚤", listOf("lancha")),
        EmojiEntry("🛳️", listOf("crucero")),
        EmojiEntry("⛴️", listOf("ferry")),
        EmojiEntry("🚢", listOf("barco")),
        EmojiEntry("⚓", listOf("ancla")),
        EmojiEntry("🚧", listOf("construccion", "obras")),
        EmojiEntry("⛽", listOf("gasolinera")),
        EmojiEntry("🚏", listOf("parada de autobus")),
        EmojiEntry("🚦", listOf("semaforo")),
        EmojiEntry("🚥", listOf("semaforo horizontal")),
        EmojiEntry("🗺️", listOf("mapa")),
        EmojiEntry("🗿", listOf("moai", "estatua")),
        EmojiEntry("🗽", listOf("estatua de la libertad")),
        EmojiEntry("🗼", listOf("torre")),
        EmojiEntry("🏰", listOf("castillo")),
        EmojiEntry("🏯", listOf("castillo japones")),
        EmojiEntry("🏟️", listOf("estadio")),
        EmojiEntry("🎡", listOf("rueda de la fortuna")),
        EmojiEntry("🎢", listOf("montaña rusa")),
        EmojiEntry("🎠", listOf("carrusel")),
        EmojiEntry("⛲", listOf("fuente")),
        EmojiEntry("⛱️", listOf("sombrilla playa")),
        EmojiEntry("🏖️", listOf("playa")),
        EmojiEntry("🏝️", listOf("isla")),
        EmojiEntry("🏔️", listOf("montaña nevada")),
        EmojiEntry("⛰️", listOf("montaña")),
        EmojiEntry("🌋", listOf("volcan")),
        EmojiEntry("🗻", listOf("monte fuji")),
        EmojiEntry("🏕️", listOf("campamento")),
        EmojiEntry("⛺", listOf("tienda de campaña")),
        EmojiEntry("🏠", listOf("casa")),
        EmojiEntry("🏡", listOf("casa con jardin")),
        EmojiEntry("🏘️", listOf("casas")),
        EmojiEntry("🏚️", listOf("casa abandonada")),
        EmojiEntry("🏗️", listOf("edificio en construccion")),
        EmojiEntry("🏭", listOf("fabrica")),
        EmojiEntry("🏢", listOf("oficina", "edificio")),
        EmojiEntry("🏬", listOf("tienda departamental")),
        EmojiEntry("🏣", listOf("oficina de correos")),
        EmojiEntry("🏥", listOf("hospital")),
        EmojiEntry("🏦", listOf("banco")),
        EmojiEntry("🏨", listOf("hotel")),
        EmojiEntry("🏪", listOf("tienda")),
        EmojiEntry("🏫", listOf("escuela")),
        EmojiEntry("💒", listOf("boda", "iglesia")),
        EmojiEntry("🏛️", listOf("museo", "gobierno")),
        EmojiEntry("⛪", listOf("iglesia")),
        EmojiEntry("🕌", listOf("mezquita")),
        EmojiEntry("🕍", listOf("sinagoga")),
        EmojiEntry("🛕", listOf("templo"))
    )

    private val objetos = listOf(
        EmojiEntry("⌚", listOf("reloj de pulsera")),
        EmojiEntry("📱", listOf("celular", "telefono")),
        EmojiEntry("💻", listOf("computadora", "laptop")),
        EmojiEntry("⌨️", listOf("teclado")),
        EmojiEntry("🖥️", listOf("computadora de escritorio")),
        EmojiEntry("🖨️", listOf("impresora")),
        EmojiEntry("🖱️", listOf("mouse")),
        EmojiEntry("💽", listOf("disco")),
        EmojiEntry("💾", listOf("disquete")),
        EmojiEntry("💿", listOf("cd")),
        EmojiEntry("📀", listOf("dvd")),
        EmojiEntry("📷", listOf("cámara", "foto")),
        EmojiEntry("📸", listOf("cámara con flash")),
        EmojiEntry("📹", listOf("videocamara")),
        EmojiEntry("🎥", listOf("camara de cine")),
        EmojiEntry("📞", listOf("telefono")),
        EmojiEntry("☎️", listOf("telefono antiguo")),
        EmojiEntry("📠", listOf("fax")),
        EmojiEntry("📺", listOf("television")),
        EmojiEntry("📻", listOf("radio")),
        EmojiEntry("🎙️", listOf("microfono de estudio")),
        EmojiEntry("⏰", listOf("reloj", "alarma")),
        EmojiEntry("⏲️", listOf("temporizador")),
        EmojiEntry("⏱️", listOf("cronometro")),
        EmojiEntry("🕰️", listOf("reloj antiguo")),
        EmojiEntry("💡", listOf("idea", "foco")),
        EmojiEntry("🔦", listOf("linterna")),
        EmojiEntry("🏮", listOf("linterna roja")),
        EmojiEntry("📔", listOf("libreta")),
        EmojiEntry("📕", listOf("libro rojo")),
        EmojiEntry("📗", listOf("libro verde")),
        EmojiEntry("📘", listOf("libro azul")),
        EmojiEntry("📙", listOf("libro naranja")),
        EmojiEntry("📚", listOf("libros")),
        EmojiEntry("📖", listOf("libro abierto")),
        EmojiEntry("🔖", listOf("marcador de libro")),
        EmojiEntry("🧾", listOf("recibo")),
        EmojiEntry("💰", listOf("dinero", "bolsa")),
        EmojiEntry("💴", listOf("yenes")),
        EmojiEntry("💵", listOf("dolares")),
        EmojiEntry("💶", listOf("euros")),
        EmojiEntry("💷", listOf("libras")),
        EmojiEntry("💸", listOf("dinero volando")),
        EmojiEntry("💳", listOf("tarjeta de credito")),
        EmojiEntry("🧮", listOf("abaco")),
        EmojiEntry("✉️", listOf("sobre", "correo")),
        EmojiEntry("📧", listOf("email")),
        EmojiEntry("📨", listOf("correo entrante")),
        EmojiEntry("📩", listOf("correo con flecha")),
        EmojiEntry("📤", listOf("bandeja de salida")),
        EmojiEntry("📥", listOf("bandeja de entrada")),
        EmojiEntry("📦", listOf("paquete", "caja")),
        EmojiEntry("📫", listOf("buzon")),
        EmojiEntry("📮", listOf("buzon de correo")),
        EmojiEntry("🗳️", listOf("urna")),
        EmojiEntry("✏️", listOf("lapiz")),
        EmojiEntry("✒️", listOf("pluma")),
        EmojiEntry("🖋️", listOf("pluma fuente")),
        EmojiEntry("🖊️", listOf("boligrafo")),
        EmojiEntry("🖌️", listOf("pincel")),
        EmojiEntry("🖍️", listOf("crayon")),
        EmojiEntry("📝", listOf("nota", "escribir")),
        EmojiEntry("💼", listOf("maletin", "trabajo")),
        EmojiEntry("📁", listOf("carpeta")),
        EmojiEntry("📂", listOf("carpeta abierta")),
        EmojiEntry("🗂️", listOf("organizador")),
        EmojiEntry("📅", listOf("calendario")),
        EmojiEntry("📆", listOf("calendario")),
        EmojiEntry("🗒️", listOf("notas")),
        EmojiEntry("🗓️", listOf("calendario espiral")),
        EmojiEntry("📇", listOf("tarjetero")),
        EmojiEntry("📈", listOf("grafico creciente")),
        EmojiEntry("📉", listOf("grafico decreciente")),
        EmojiEntry("📊", listOf("grafico de barras")),
        EmojiEntry("📋", listOf("portapapeles")),
        EmojiEntry("📌", listOf("chincheta")),
        EmojiEntry("📍", listOf("ubicacion", "pin")),
        EmojiEntry("📎", listOf("clip")),
        EmojiEntry("🖇️", listOf("clips")),
        EmojiEntry("📏", listOf("regla")),
        EmojiEntry("📐", listOf("escuadra")),
        EmojiEntry("✂️", listOf("tijeras")),
        EmojiEntry("🗃️", listOf("archivo")),
        EmojiEntry("🗄️", listOf("archivero")),
        EmojiEntry("🗑️", listOf("papelera", "basura")),
        EmojiEntry("🔒", listOf("candado cerrado")),
        EmojiEntry("🔓", listOf("candado abierto")),
        EmojiEntry("🔏", listOf("candado con pluma")),
        EmojiEntry("🔐", listOf("candado con llave")),
        EmojiEntry("🔑", listOf("llave")),
        EmojiEntry("🗝️", listOf("llave antigua")),
        EmojiEntry("🔨", listOf("martillo")),
        EmojiEntry("🪓", listOf("hacha")),
        EmojiEntry("⛏️", listOf("pico")),
        EmojiEntry("🔧", listOf("llave inglesa")),
        EmojiEntry("🔩", listOf("tornillo")),
        EmojiEntry("⚙️", listOf("engranaje", "ajustes")),
        EmojiEntry("🗜️", listOf("prensa")),
        EmojiEntry("⚖️", listOf("balanza", "justicia")),
        EmojiEntry("🔗", listOf("cadena", "enlace")),
        EmojiEntry("⛓️", listOf("cadenas")),
        EmojiEntry("🧰", listOf("caja de herramientas")),
        EmojiEntry("🧲", listOf("iman")),
        EmojiEntry("⚗️", listOf("alambique")),
        EmojiEntry("🧪", listOf("tubo de ensayo")),
        EmojiEntry("🧫", listOf("placa de petri")),
        EmojiEntry("🔬", listOf("microscopio")),
        EmojiEntry("🔭", listOf("telescopio")),
        EmojiEntry("📡", listOf("antena")),
        EmojiEntry("💉", listOf("jeringa", "vacuna")),
        EmojiEntry("🩹", listOf("curita")),
        EmojiEntry("💊", listOf("pastilla", "medicina")),
        EmojiEntry("🩺", listOf("estetoscopio")),
        EmojiEntry("🚪", listOf("puerta")),
        EmojiEntry("🪞", listOf("espejo")),
        EmojiEntry("🪟", listOf("ventana")),
        EmojiEntry("🛏️", listOf("cama")),
        EmojiEntry("🛋️", listOf("sofa")),
        EmojiEntry("🚽", listOf("inodoro")),
        EmojiEntry("🚿", listOf("regadera")),
        EmojiEntry("🛁", listOf("bañera")),
        EmojiEntry("🧴", listOf("botella", "shampoo")),
        EmojiEntry("🧷", listOf("seguro")),
        EmojiEntry("🧹", listOf("escoba")),
        EmojiEntry("🧺", listOf("canasta")),
        EmojiEntry("🧻", listOf("papel higienico")),
        EmojiEntry("🪣", listOf("cubeta")),
        EmojiEntry("🧼", listOf("jabon")),
        EmojiEntry("🪥", listOf("cepillo de dientes")),
        EmojiEntry("🧽", listOf("esponja")),
        EmojiEntry("🧯", listOf("extintor")),
        EmojiEntry("🛒", listOf("carrito de compras"))
    )

    private val simbolos = listOf(
        EmojiEntry("✅", listOf("check", "listo", "hecho")),
        EmojiEntry("☑️", listOf("check en caja")),
        EmojiEntry("✔️", listOf("check")),
        EmojiEntry("❎", listOf("no", "equis en caja")),
        EmojiEntry("➕", listOf("mas", "sumar")),
        EmojiEntry("➖", listOf("menos", "restar")),
        EmojiEntry("➗", listOf("dividir")),
        EmojiEntry("✖️", listOf("multiplicar")),
        EmojiEntry("♾️", listOf("infinito")),
        EmojiEntry("‼️", listOf("doble exclamacion")),
        EmojiEntry("⁉️", listOf("interrogacion exclamacion")),
        EmojiEntry("❓", listOf("pregunta", "duda")),
        EmojiEntry("❔", listOf("pregunta blanca")),
        EmojiEntry("❗", listOf("exclamación", "importante")),
        EmojiEntry("❕", listOf("exclamacion blanca")),
        EmojiEntry("〰️", listOf("linea ondulada")),
        EmojiEntry("💯", listOf("cien", "perfecto")),
        EmojiEntry("🔟", listOf("diez")),
        EmojiEntry("🔢", listOf("numeros")),
        EmojiEntry("#️⃣", listOf("almohadilla", "hashtag")),
        EmojiEntry("*️⃣", listOf("asterisco")),
        EmojiEntry("⏸️", listOf("pausa")),
        EmojiEntry("▶️", listOf("play", "reproducir")),
        EmojiEntry("⏹️", listOf("detener")),
        EmojiEntry("⏺️", listOf("grabar")),
        EmojiEntry("⏭️", listOf("siguiente")),
        EmojiEntry("⏮️", listOf("anterior")),
        EmojiEntry("🔀", listOf("aleatorio")),
        EmojiEntry("🔁", listOf("repetir")),
        EmojiEntry("🔂", listOf("repetir uno")),
        EmojiEntry("🔼", listOf("subir")),
        EmojiEntry("🔽", listOf("bajar")),
        EmojiEntry("⬆️", listOf("flecha arriba")),
        EmojiEntry("⬇️", listOf("flecha abajo")),
        EmojiEntry("⬅️", listOf("flecha izquierda")),
        EmojiEntry("➡️", listOf("flecha derecha")),
        EmojiEntry("↗️", listOf("flecha diagonal")),
        EmojiEntry("↘️", listOf("flecha diagonal")),
        EmojiEntry("↙️", listOf("flecha diagonal")),
        EmojiEntry("↖️", listOf("flecha diagonal")),
        EmojiEntry("↕️", listOf("flecha vertical")),
        EmojiEntry("↔️", listOf("flecha horizontal")),
        EmojiEntry("🔄", listOf("actualizar", "girar")),
        EmojiEntry("🔃", listOf("recargar")),
        EmojiEntry("🔅", listOf("brillo bajo")),
        EmojiEntry("🔆", listOf("brillo alto")),
        EmojiEntry("📶", listOf("señal", "wifi")),
        EmojiEntry("📳", listOf("modo vibrar")),
        EmojiEntry("📴", listOf("apagado")),
        EmojiEntry("♻️", listOf("reciclaje")),
        EmojiEntry("⚜️", listOf("flor de lis")),
        EmojiEntry("🔱", listOf("triden")),
        EmojiEntry("📛", listOf("gafete de nombre")),
        EmojiEntry("🔰", listOf("principiante")),
        EmojiEntry("⭕", listOf("circulo")),
        EmojiEntry("☮️", listOf("paz")),
        EmojiEntry("✝️", listOf("cruz")),
        EmojiEntry("☪️", listOf("islam")),
        EmojiEntry("🕉️", listOf("hinduismo")),
        EmojiEntry("☸️", listOf("budismo")),
        EmojiEntry("✡️", listOf("estrella de david")),
        EmojiEntry("☯️", listOf("yin yang")),
        EmojiEntry("♈", listOf("aries")),
        EmojiEntry("♉", listOf("tauro")),
        EmojiEntry("♊", listOf("geminis")),
        EmojiEntry("♋", listOf("cancer")),
        EmojiEntry("♌", listOf("leo")),
        EmojiEntry("♍", listOf("virgo")),
        EmojiEntry("♎", listOf("libra")),
        EmojiEntry("♏", listOf("escorpio")),
        EmojiEntry("♐", listOf("sagitario")),
        EmojiEntry("♑", listOf("capricornio")),
        EmojiEntry("♒", listOf("acuario")),
        EmojiEntry("♓", listOf("piscis")),
        EmojiEntry("🆗", listOf("ok")),
        EmojiEntry("🆕", listOf("nuevo")),
        EmojiEntry("🆒", listOf("cool")),
        EmojiEntry("🆓", listOf("gratis")),
        EmojiEntry("🆙", listOf("subir nivel")),
        EmojiEntry("🔤", listOf("abecedario")),
        EmojiEntry("🔡", listOf("minusculas")),
        EmojiEntry("🔠", listOf("mayusculas")),
        EmojiEntry("✴️", listOf("estrella asterisco")),
        EmojiEntry("🆚", listOf("versus", "vs")),
        EmojiEntry("💮", listOf("flor blanca")),
        EmojiEntry("🚫", listOf("prohibido")),
        EmojiEntry("⛔", listOf("prohibido el paso")),
        EmojiEntry("🚭", listOf("no fumar")),
        EmojiEntry("🚯", listOf("no tirar basura")),
        EmojiEntry("🚱", listOf("agua no potable")),
        EmojiEntry("🚳", listOf("no bicicletas")),
        EmojiEntry("🚷", listOf("no peatones")),
        EmojiEntry("📵", listOf("no celulares")),
        EmojiEntry("🔞", listOf("mayores de edad")),
        EmojiEntry("☢️", listOf("radioactivo")),
        EmojiEntry("☣️", listOf("biopeligro")),
        EmojiEntry("⚠️", listOf("advertencia", "cuidado")),
        EmojiEntry("🚸", listOf("niños cruzando")),
        EmojiEntry("💢", listOf("enojo")),
        EmojiEntry("💫", listOf("mareo", "estrellas")),
        EmojiEntry("💦", listOf("sudor", "gotas")),
        EmojiEntry("💤", listOf("dormir")),
        EmojiEntry("🕳️", listOf("agujero")),
        EmojiEntry("💬", listOf("mensaje", "hablar")),
        EmojiEntry("🗨️", listOf("dialogo")),
        EmojiEntry("🗯️", listOf("enojo hablar")),
        EmojiEntry("💭", listOf("pensamiento"))
    )

    private val banderas = listOf(
        EmojiEntry("🏳️", listOf("bandera blanca")),
        EmojiEntry("🏴", listOf("bandera negra")),
        EmojiEntry("🏁", listOf("bandera de meta")),
        EmojiEntry("🚩", listOf("bandera roja")),
        EmojiEntry("🇲🇽", listOf("mexico", "bandera")),
        EmojiEntry("🇪🇸", listOf("españa", "bandera")),
        EmojiEntry("🇺🇸", listOf("estados unidos", "bandera")),
        EmojiEntry("🇦🇷", listOf("argentina", "bandera")),
        EmojiEntry("🇨🇴", listOf("colombia", "bandera")),
        EmojiEntry("🇨🇱", listOf("chile", "bandera")),
        EmojiEntry("🇵🇪", listOf("peru", "bandera")),
        EmojiEntry("🇻🇪", listOf("venezuela", "bandera")),
        EmojiEntry("🇪🇨", listOf("ecuador", "bandera")),
        EmojiEntry("🇬🇹", listOf("guatemala", "bandera")),
        EmojiEntry("🇨🇺", listOf("cuba", "bandera")),
        EmojiEntry("🇧🇴", listOf("bolivia", "bandera")),
        EmojiEntry("🇩🇴", listOf("republica dominicana", "bandera")),
        EmojiEntry("🇭🇳", listOf("honduras", "bandera")),
        EmojiEntry("🇵🇾", listOf("paraguay", "bandera")),
        EmojiEntry("🇸🇻", listOf("el salvador", "bandera")),
        EmojiEntry("🇳🇮", listOf("nicaragua", "bandera")),
        EmojiEntry("🇨🇷", listOf("costa rica", "bandera")),
        EmojiEntry("🇵🇦", listOf("panama", "bandera")),
        EmojiEntry("🇺🇾", listOf("uruguay", "bandera")),
        EmojiEntry("🇵🇷", listOf("puerto rico", "bandera")),
        EmojiEntry("🇧🇷", listOf("brasil", "bandera")),
        EmojiEntry("🇨🇦", listOf("canada", "bandera")),
        EmojiEntry("🇫🇷", listOf("francia", "bandera")),
        EmojiEntry("🇩🇪", listOf("alemania", "bandera")),
        EmojiEntry("🇮🇹", listOf("italia", "bandera")),
        EmojiEntry("🇬🇧", listOf("reino unido", "bandera")),
        EmojiEntry("🇵🇹", listOf("portugal", "bandera")),
        EmojiEntry("🇯🇵", listOf("japon", "bandera")),
        EmojiEntry("🇨🇳", listOf("china", "bandera")),
        EmojiEntry("🇰🇷", listOf("corea del sur", "bandera")),
        EmojiEntry("🇮🇳", listOf("india", "bandera")),
        EmojiEntry("🇷🇺", listOf("rusia", "bandera"))
    )

    data class Category(val name: String, val icon: String, val items: List<EmojiEntry>)

    val categories: List<Category> = listOf(
        Category("Caritas", "😀", smileys),
        Category("Gestos", "👋", gestos),
        Category("Animales", "🐶", animales),
        Category("Comida", "🍎", comida),
        Category("Actividades", "⚽", actividades),
        Category("Viajes", "🚗", viajes),
        Category("Objetos", "💡", objetos),
        Category("Símbolos", "✅", simbolos),
        Category("Banderas", "🏳️", banderas)
    )

    val all: List<EmojiEntry> =
        smileys + gestos + animales + comida + actividades + viajes + objetos + simbolos + banderas

    fun search(query: String): List<EmojiEntry> {
        if (query.isBlank()) return all
        val q = query.lowercase()
        return all.filter { entry -> entry.keywords.any { it.contains(q) } || entry.emoji == q }
    }
}
